version: "3.8"

services:

  web:
    build:
      context: ../backend/
      dockerfile: ./DOCKERFILE
    image: aceplaceweb
    command: python main.py
    container_name: fastapi
    env_file:
      - ./environments/db.env
      - ./environments/backend.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../backend/:/usr/src/backend
    depends_on:
      - db
    networks:
      - web-app
  
  db:
    image: mongo:latest
    container_name: "${MONGODB_HOST}"
    env_file:
      - ./environments/db.env
    ports: 
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongo-data:/data/db
      - mongo-log:/var/log/mongodb
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./scripts/script.sh:/docker-entrypoint-initdb.d/script.sh:ro
    restart: on-failure
    networks:
      - web-app

volumes:
  mongo-data:
    driver: local
  mongo-log:
    driver: local

networks:
  web-app:
    name: web-app
    driver: bridge